[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# SPA redirect for client-side routing (fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
